#!/usr/bin/env ruby
PATH = File.expand_path('~/RyPassSource')
require "#{PATH}/config/setup"

begin
  params = Exec.set_params
  if params[:action] == :uninstall || params[:action] == :display_commands
    Exec.send(params[:action])
  elsif params[:action]
    Exec.send(params[:action], params)
  end
rescue Interrupt
  puts "\nThank you for using RyPass"
  exit
end
